/**
 * GitHub Action entry point: collect public profile data, render the cards and
 * publish them to the readmeops branch of the repository. Node built-ins only.
 */
import { execFile } from "node:child_process";
import { appendFile, mkdir, mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import {
  assertPublicSafe,
  buildView,
  collectProfile,
  demoProfile,
  isLogin,
  OptionsError,
  OUTPUT_BRANCH,
  parseOptions,
  PrivacyError,
  readmeSnippet,
  renderCards,
  type CardFile,
  type ProfileData,
} from "@readmeops/core";

const execFileP = promisify(execFile);

/** GitHub maps input "dry-run" to env INPUT_DRY-RUN (upper case, spaces to underscores). */
export function input(name: string, fallback = ""): string {
  const value = process.env[`INPUT_${name.replace(/ /g, "_").toUpperCase()}`];
  return value !== undefined && value.trim() !== "" ? value : fallback;
}

export function bool(name: string, fallback: boolean): boolean {
  const v = input(name, String(fallback)).trim().toLowerCase();
  if (["true", "1", "yes"].includes(v)) return true;
  if (["false", "0", "no"].includes(v)) return false;
  throw new OptionsError(`Input "${name}" must be true or false.`);
}

function escapeCommand(value: string): string {
  return value.replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
}

const log = (m: string) => process.stdout.write(`${m}\n`);
const warn = (m: string) => process.stdout.write(`::warning::${escapeCommand(m)}\n`);
const fail = (m: string) => process.stdout.write(`::error::${escapeCommand(m)}\n`);

async function setOutput(name: string, value: string): Promise<void> {
  const file = process.env["GITHUB_OUTPUT"];
  if (!file) return;
  const delimiter = `readmeops_${Math.random().toString(36).slice(2)}`;
  await appendFile(file, `${name}<<${delimiter}\n${value}\n${delimiter}\n`);
}

async function summary(markdown: string): Promise<void> {
  const file = process.env["GITHUB_STEP_SUMMARY"];
  if (file) await appendFile(file, `${markdown}\n`);
}

async function git(args: string[], cwd: string): Promise<string> {
  const { stdout } = await execFileP("git", args, { cwd });
  return stdout;
}

const BRANCH_README = `# readmeops cards

Generated by the readmeops workflow. Every run replaces this branch with a single
commit, so do not edit files here. Your README links to them.
`;

/** Replaces the output branch with one commit holding `files`, unless nothing changed. */
export async function publish(files: CardFile[], remote: string, token: string): Promise<"unchanged" | "pushed"> {
  const dir = await mkdtemp(join(tmpdir(), "readmeops-"));
  const auth = token ? ["-c", `http.extraheader=AUTHORIZATION: basic ${Buffer.from(`x-access-token:${token}`).toString("base64")}`] : [];
  try {
    const current = new Map<string, string>();
    try {
      await git([...auth, "clone", "--quiet", "--depth", "1", "--single-branch", "--branch", OUTPUT_BRANCH, remote, "current"], dir);
      for (const f of await readdir(join(dir, "current"))) {
        if (f.endsWith(".svg")) current.set(f, await readFile(join(dir, "current", f), "utf8"));
      }
    } catch {
      // The branch does not exist yet.
    }
    if (current.size === files.length && files.every((f) => current.get(f.path) === f.svg)) return "unchanged";

    const out = join(dir, "out");
    await mkdir(out);
    await git(["init", "--quiet", "-b", OUTPUT_BRANCH], out);
    for (const f of files) await writeFile(join(out, f.path), f.svg);
    await writeFile(join(out, "README.md"), BRANCH_README);
    await git(["add", "--all"], out);
    await git(
      ["-c", "user.name=github-actions[bot]", "-c", "user.email=41898282+github-actions[bot]@users.noreply.github.com", "commit", "--quiet", "-m", "readmeops: refresh cards"],
      out,
    );
    await git([...auth, "push", "--force", "--quiet", remote, `HEAD:refs/heads/${OUTPUT_BRANCH}`], out);
    return "pushed";
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

export async function main(): Promise<number> {
  const token = input("token").trim();
  if (token) log(`::add-mask::${token}`);
  const options = parseOptions({
    look: input("look"),
    cards: input("cards"),
    headline: input("headline"),
    programs: input("programs"),
    blog: input("blog"),
  });
  const repository = process.env["GITHUB_REPOSITORY"] ?? "";
  const user = input("user", process.env["GITHUB_REPOSITORY_OWNER"] ?? repository.split("/")[0] ?? "").trim();
  if (!isLogin(user)) throw new OptionsError(`"${user}" is not a valid GitHub username. Set the user input.`);
  const dryRun = bool("dry-run", false);
  const demo = process.env["READMEOPS_DEMO"];

  log(`::group::readmeops: ${options.look} look for ${user}`);
  let data: ProfileData;
  if (demo) {
    // Fictional demo profile, for trying the Action without calling the GitHub API.
    data = demoProfile(new Date(), demo === "private" ? "private" : "public");
    data.headline = options.headline ?? data.headline;
    if (options.programs.length) data.programs = options.programs;
    assertPublicSafe(data);
  } else {
    if (!token) throw new OptionsError("No token. Keep the default token input (the workflow's GITHUB_TOKEN).");
    data = await collectProfile({
      user,
      token,
      mode: "public",
      feeds: options.feeds,
      programs: options.programs,
      headline: options.headline,
      log,
    });
  }
  const view = buildView(data);
  const files = renderCards(view, options.look, options.cards);
  log(`rendered ${files.length} files: ${files.map((f) => f.path).join(", ")}`);
  log("::endgroup::");
  for (const w of data.warnings) warn(w);

  let result: "unchanged" | "pushed" | "dry run" = "dry run";
  if (!dryRun) {
    const remote = process.env["READMEOPS_REMOTE"] ?? `${process.env["GITHUB_SERVER_URL"] ?? "https://github.com"}/${repository}.git`;
    result = await publish(files, remote, token);
  }
  await setOutput("changed", String(result === "pushed"));
  await setOutput("files", files.map((f) => f.path).join("\n"));

  const blogUrl = options.feeds[0] ? `https://${new URL(options.feeds[0]).host}` : view.websiteUrl;
  await summary(
    [
      `### readmeops: ${result === "pushed" ? "cards updated" : result === "unchanged" ? "no changes" : "dry run"}`,
      "",
      `${files.length} files on the \`${OUTPUT_BRANCH}\` branch (${options.look} look). Paste this into your README once:`,
      "",
      "```html",
      readmeSnippet(user, options.cards, blogUrl, repository || `${user}/${user}`),
      "```",
      ...(data.warnings.length ? ["", "Warnings:", ...data.warnings.map((w) => `- ${w}`)] : []),
    ].join("\n"),
  );
  log(result === "pushed" ? `pushed updated cards to ${OUTPUT_BRANCH}` : result === "unchanged" ? "cards unchanged" : "dry run: nothing pushed");
  return 0;
}

if (process.env["GITHUB_ACTIONS"] === "true" || process.env["READMEOPS_ACTION_RUN"] === "1") {
  main().then(
    (code) => process.exit(code),
    (err: unknown) => {
      if (err instanceof PrivacyError || err instanceof OptionsError) fail(err.message);
      else fail(`readmeops failed: ${(err as Error).message ?? String(err)}`);
      process.exit(1);
    },
  );
}
