#!/usr/bin/env python3
"""Regenerate packages/core/src/fonts/data.ts from the upstream OFL fonts.

The looks embed these fonts in every SVG, so text renders identically on every
machine. Each face is cut down to Latin (U+0020-00FF plus common punctuation);
anything else falls back to the viewer's system fonts.

Usage (from the repo root):
  npm i --no-save @fontsource/jetbrains-mono@5 @fontsource/geist-sans@5 @fontsource/geist-mono@5 \
        @fontsource/barlow-semi-condensed@5 @fontsource/bricolage-grotesque@5
  pip install fonttools brotli
  python3 scripts/subset-fonts.py node_modules/@fontsource
"""
import base64
import io
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

# key, CSS family, weight, fontsource package, file stem
FACES = [
    ("mono-400", "RO Mono", 400, "jetbrains-mono", "jetbrains-mono-latin-400-normal"),
    ("mono-700", "RO Mono", 700, "jetbrains-mono", "jetbrains-mono-latin-700-normal"),
    ("sans-400", "RO Sans", 400, "geist-sans", "geist-sans-latin-400-normal"),
    ("sans-500", "RO Sans", 500, "geist-sans", "geist-sans-latin-500-normal"),
    ("sans-600", "RO Sans", 600, "geist-sans", "geist-sans-latin-600-normal"),
    ("code-400", "RO Code", 400, "geist-mono", "geist-mono-latin-400-normal"),
    ("cond-600", "RO Cond", 600, "barlow-semi-condensed", "barlow-semi-condensed-latin-600-normal"),
    ("display-500", "RO Display", 500, "bricolage-grotesque", "bricolage-grotesque-latin-500-normal"),
    ("display-800", "RO Display", 800, "bricolage-grotesque", "bricolage-grotesque-latin-800-normal"),
]
UPSTREAM = {
    "jetbrains-mono": ("JetBrains Mono", "https://github.com/JetBrains/JetBrainsMono"),
    "geist-sans": ("Geist", "https://github.com/vercel/geist-font"),
    "geist-mono": ("Geist Mono", "https://github.com/vercel/geist-font"),
    "barlow-semi-condensed": ("Barlow Semi Condensed", "https://github.com/jpt/barlow"),
    "bricolage-grotesque": ("Bricolage Grotesque", "https://github.com/ateliertriay/bricolage"),
}
EXTRA = [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x2212]
CODEPOINTS = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) + EXTRA


def cut(path):
    font = TTFont(path)
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = ["kern", "liga", "tnum", "case"]
    opts.hinting = False
    opts.desubroutinize = True
    opts.name_IDs = ["*"]
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=CODEPOINTS)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    font = TTFont(io.BytesIO(buf.getvalue()))
    cmap, hmtx = font.getBestCmap(), font["hmtx"]
    advances = [hmtx[cmap[cp]][0] if cp in cmap else 0 for cp in CODEPOINTS]
    return buf.getvalue(), font["head"].unitsPerEm, advances


def license_header(pkg_dir):
    text = open(os.path.join(pkg_dir, "LICENSE"), encoding="utf-8").read()
    head = text.split("SIL OPEN FONT LICENSE")[0]
    return "\n".join(l.rstrip() for l in head.splitlines() if l.strip() and not l.startswith("---")).strip(), text


def main(src):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = os.path.join(root, "packages", "core", "src", "fonts")
    os.makedirs(out_dir, exist_ok=True)
    lines = [
        "// Generated by scripts/subset-fonts.py from the upstream OFL-1.1 fonts. Do not edit.",
        "// Licenses: ./LICENSE-fonts.md",
        f"export const CODEPOINTS: readonly number[] = {CODEPOINTS};",
        "export interface FaceData { family: string; weight: number; upm: number; advances: readonly number[]; woff2: string }",
        "export const FACES: Readonly<Record<string, FaceData>> = {",
    ]
    total = 0
    for key, family, weight, pkg, stem in FACES:
        data, upm, adv = cut(os.path.join(src, pkg, "files", stem + ".woff2"))
        total += len(data)
        b64 = base64.b64encode(data).decode()
        lines.append(f'  "{key}": {{ family: "{family}", weight: {weight}, upm: {upm}, advances: {adv}, woff2: "{b64}" }},')
        print(f"{key:12} {len(data):6} bytes")
    lines.append("};")
    open(os.path.join(out_dir, "data.ts"), "w").write("\n".join(lines) + "\n")

    notices, ofl = [], None
    for pkg, (name, url) in UPSTREAM.items():
        header, full = license_header(os.path.join(src, pkg))
        notices.append(f"## {name}\n\nSource: {url}\n\n{header}\n")
        ofl = ofl or "SIL OPEN FONT LICENSE" + full.split("SIL OPEN FONT LICENSE", 1)[1]
    open(os.path.join(out_dir, "LICENSE-fonts.md"), "w").write(
        "# Embedded fonts\n\nThe looks embed Latin subsets of these fonts. Each is licensed under the\n"
        "SIL Open Font License 1.1, reproduced once at the end of this file.\n\n"
        + "\n".join(notices) + "\n---\n\n```text\n" + ofl.strip() + "\n```\n")
    print(f"total {total} bytes")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
